# docker-compose.yml
version: '2'
services:
    prometheus:
        image: prom/prometheus:v2.11.1
        volumes:
            - prometheus_data:/prometheus
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./config/prometheus/aerospike_rules.yml:/etc/prometheus/aerospike_rules.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - '9090:9090'

    alertmanager:
        image: prom/alertmanager
        volumes:
            - alertmanager_data:/alertmanager
            - ./config/prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml
        command:
            - '--config.file=/etc/prometheus/alertmanager.yml'
            - '--storage.path=/alertmanager'
        ports:
            - 9093:9093

    grafana:
            image: grafana/grafana:6.3.2
            volumes:
                - grafana_data:/var/lib/grafana
                - ./config/grafana/plugins:/grafana_plugins
                - ./config/grafana/dashboards/:/var/lib/grafana/dashboards/
                - ./config/grafana/provisioning/:/etc/grafana/provisioning/
            environment:
                - GF_SECURITY_ADMIN_PASSWORD=pass
                - GF_PATHS_PLUGINS=/grafana_plugins
            depends_on:
                - prometheus
            ports:
                - "3000:3000"
volumes:
        prometheus_data: {}
        alertmanager_data: {}
        grafana_data: {}
        grafana_plugins: {}
