global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
- "/run/secrets/aerospike_rules.yaml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'aerospike'
  dns_sd_configs:
  - names:
    - 'tasks.exporter'
    type: 'A'
    port: 9145